[custom]
;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/hydenli/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/hydenli/rule/refs/heads/main/ProxyLite.list
ruleset=💰 Crypto,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Crypto/Crypto.list
ruleset=🤖 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/hydenli/rule/refs/heads/main/AI.list
ruleset=🥸 Hydenli,https://raw.githubusercontent.com/hydenli/rule/refs/heads/main/proxy1.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📢 FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
#ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=💧 Copilot,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
;ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
;ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
;ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
;ruleset=🐦‍⬛ Twitter,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=📦 国外下载,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Docker/Docker.yaml
ruleset=📦 国外下载,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Ubuntu/Ubuntu.yaml


ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=🚀 节点选择`select`[]🔯 高节故转`[]♻️ 高速节点`[]🔯 便宜高故`[]♻️ 便宜高速`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 便宜高速`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🐸 手动切换`[]REJECT`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]⏩ 香港均衡`[]🐸 手动切换`[]REJECT
custom_proxy_group=🤖 AI`select`[]🔯 AI故转`[]🔯🇸🇬 师城故转`[]🔯🇺🇸 美国故转`[]💡 GPT`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]REJECT
custom_proxy_group=💧 Copilot`select`[]🔯 AI故转`[]🚀 节点选择`[]🐸 手动切换`[]REJECT
custom_proxy_group=🪟 Microsoft`select`[]🔯 AI故转`[]🚀 节点选择`[]♻️ 高速节点`[]🐸 手动切换`[]REJECT`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🔯 AI故转`[]💡 Gemini`[]💡 GPT`[]🚀 节点选择`[]♻️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=📢 FCM`select`[]🚀 节点选择`[]🔯 AI故转`[]🐸 手动切换`[]REJECT
custom_proxy_group=💰 Crypto`select`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`[]🏳️ 台湾节点`[]🐸 手动切换`[]REJECT
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🔯 AI故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`[]🐸 手动切换`[]🚀 节点选择
;custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]🕊 便宜节点`[]🐸 手动切换`[]REJECT
;custom_proxy_group=🐦‍⬛ Twitter`select`[]🚀 节点选择`[]🕊 便宜节点`[]🐸 手动切换`[]REJECT
custom_proxy_group=🥸 Hydenli`select`[]🚀 节点选择`[]🔯 AI故转`[]🐸 手动切换`[]REJECT
;custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]🎥 奈飞节点`[]🐸 手动切换`[]REJECT
;custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🐸 手动切换`[]REJECT
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]♻️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=📦 国外下载`select`[]🚀 节点选择`[]♻️ 便宜高速`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🐸 手动切换`[]⏩ 香港均衡`[]REJECT
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换

custom_proxy_group=🐸 手动切换`select`.*
;custom_proxy_group=🏡 家宽节点`select`!!GROUP=Good!!(家宽|家庭)
;custom_proxy_group=🕊 便宜节点`select`!!GROUP=Bad
;custom_proxy_group=🎩 专线节点`select`!!GROUP=Good!!(专线|2x|3x|4x|2.5x|3.5x|4.5x|6x|8x)
custom_proxy_group=🔯 高节故转`fallback`!!GROUP=Good!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|台湾|台北|中華|TW|Taiwan))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x|6x|8x|3.5x)).)*$`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🔯 AI故转`fallback`!!GROUP=Good!!(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|坡|狮城|SG|Singapore|台湾))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 AI故转`fallback`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(?=.*(日本|川日|东京|大阪|泉日|埼玉|JP|Japan|新加坡|坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x)).)*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯🇸🇬 师城故转`fallback`!!GROUP=Good!!(?=.*(GPT|gpt))(?=.*(新加坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x)).)*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯🇺🇸 美国故转`fallback`!!GROUP=Good!!(?=.*(GPT|gpt))(?=.*(美国|US))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x)).)*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🔯🇯🇵 日本故转`fallback`!!GROUP=Good!!(?=.*(GPT|gpt))(?=.*(日本|川日|东京|大阪|泉日|埼玉|JP|Japan))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x)).)*`http://www.gstatic.com/generate_204`300,,50



custom_proxy_group=🔯 便宜高故`fallback`!!GROUP=Bad!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|台湾|台北|中華|TW|Taiwan))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x|6x|8x|3.5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=💡 GPT`select`!!GROUP=Good!!(GPT|gpt)
custom_proxy_group=💡 Gemini`select`!!GROUP=Good!!(Gemini)


custom_proxy_group=⏩ 香港均衡`load-balance`!!GROUPID=!0!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x|6x|8x)).)*$`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=⏩ 负载均衡`load-balance`!!GROUP=Bad!!(?=.*)^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x|6x|8x)).)*$`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=♻️ 自动选择`url-test`!!GROUP=Good!!^((?!(2x|2.5x|3x|3.5x|4x|6x|8x)).)*$`http://www.gstatic.com/generate_204`300,,50  
custom_proxy_group=♻️ 高速节点`url-test`!!GROUP=Good!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|台湾|台北|中華|TW|Taiwan|新加坡|坡|狮城|SG|Singapore))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x|6x|8x|3.5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 便宜高速`url-test`!!GROUP=Bad!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|台湾|台北|中華|TW|Taiwan|新加坡|坡|狮城|SG|Singapore))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x|6x|8x|3.5x)).)*$`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇭🇰 香港节点`select`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))
custom_proxy_group=🏳️ 台湾节点`select`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(?=.*(台湾|台北|中華|TW|Taiwan))
custom_proxy_group=🇯🇵 日本节点`select`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))
custom_proxy_group=🇸🇬 狮城节点`select`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(?=.*(新加坡|坡|狮城|SG|Singapore))
custom_proxy_group=🇺🇲 美国节点`select`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|America))
custom_proxy_group=🌐 其他地区`select`!!GROUP=Good!!(?=.*(GPT|gpt|Gemini|gemini))(^(?!.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|坡|狮城|SG|Singapore|台湾|台北|中華|TW|Taiwan|美|US|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|3.5x|3.5|2.5|4.5|6x|8x)).*)

custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🏠 流量信息`select`(剩余|流量|到期)

custom_proxy_group=good`select`!!GROUP=Good
custom_proxy_group=bad`select`!!GROUP=Bad

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true











